### ISSUE TITLE
Exception returned by the getITypeMainByWorkspaceScope function

### ISSUE THREAD

**Issue by StephaneMangin** [gemoc/modelanimation#4]
Since the commit eeadb6ff480cb9b02ff9eeeb20db6ed347a0ec8f, an exception systematically occurs at the runtime of a xDsml instantiation.

Here comes the stack-trace : 
<code>
!ENTRY org.gemoc.execution.sequential.javaengine.ui 4 0 2016-03-29 14:55:37.665
!MESSAGE Error occured when starting execution engine: Index: 0, Size: 0 (see inner exception).
!STACK 0
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
    at java.util.ArrayList.rangeCheck(Unknown Source)
    at java.util.ArrayList.get(Unknown Source)
    at org.gemoc.execution.sequential.javaengine.PlainK3ExecutionEngine.getITypeMainByWorkspaceScope(PlainK3ExecutionEngine.java:356)
    at org.gemoc.execution.sequential.javaengine.PlainK3ExecutionEngine.findBundle(PlainK3ExecutionEngine.java:285)
    at org.gemoc.execution.sequential.javaengine.PlainK3ExecutionEngine.initialize(PlainK3ExecutionEngine.java:92)
    at org.gemoc.execution.sequential.javaengine.ui.launcher.Launcher.launch(Launcher.java:111)
    at org.eclipse.debug.internal.core.LaunchConfiguration.launch(LaunchConfiguration.java:885)
    at org.eclipse.debug.internal.core.LaunchConfiguration.launch(LaunchConfiguration.java:739)
    at org.eclipse.debug.internal.ui.DebugUIPlugin.buildAndLaunch(DebugUIPlugin.java:1039)
    at org.eclipse.debug.internal.ui.DebugUIPlugin$8.run(DebugUIPlugin.java:1256)
    at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)
</code>

The problem comes from an empty list access (`binaryType`) in the return of the `getITypeMainByWorkspaceScope` function.

**Comment by fcoulon** [comment]
I guess `PlainK3ExecutionEngine.getITypeMainByWorkspaceScope()` should end with :

```
if(!binaryType.isEmpty(){
    return binaryType.get(0);
}
return null;
```

The code before eeadb6ff480cb9b02ff9eeeb20db6ed347a0ec8f return null if the DefaultSearchRequestor match nothing.
